export const sonnet = () => {
    const original = document.getElementById("targetText");
    const sonnet = document.getElementById("sonnet");
    const clone = sonnet.cloneNode(true)
    original.replaceWith(clone)
    document.getElementById("sonnet").id = "targetText"
    alert("A reworking of Shakespeare's Sonnet 18 with the Fade-out Erasure Style.");
}

export const internetPoet = () => {
  alert("Poem text was generated by a AI!");
  const canvas = document.getElementById("targetText");
  window.clearText("targetText");
  canvas.style.width = 500;
  canvas.style.height = 500;
  canvas.style.backgroundColor = "white";
  window.generateText(
    "don’t mistake\nsalt for sugar\nit never really left the hands\nof those who broke you\nthe thing\nworth holding onto\nwould not come for you\nyour sweetness belongs\nonly to yourself\n"
  );
  canvas.style.backgroundImage = "url('../images/cake.jpg')"
  canvas.style.fontFamily = "Times";
};