// export const sonnet = () => {
//     const original = document.getElementById("targetText");
//     const sonnet = document.getElementById("sonnet");
//     const clone = sonnet.cloneNode(true)
//     original.replaceWith(clone)
//     document.getElementById("sonnet").id = "targetText"
//     alert("A reworking of Shakespeare's Sonnet 18 with the Fade-out Erasure Style.");



// }
export const demo = (name) => {
    const original = document.getElementById("targetText");
    const sonnet = document.getElementById(name);
    const clone = sonnet.cloneNode(true)
    original.replaceWith(clone)
    document.getElementById(name).id = "targetText"
    document.getElementById("targetText").childNodes.forEach( (child) => {
            child.addEventListener("click", function () {
              if (window.erasureSelection === "character" && window.eraseable) {
                this.classList.toggle(`${window.erasureOption}`);
              } else if (
                window.erasureSelection === "word" &&
                window.eraseable
              ) {
                getWord(this).forEach((letterElement) => {
                  letterElement.classList.toggle(`${window.erasureOption}`);
                });
              }
            });
    })

    switch (name) {
        case "sonnet":
            changeErasureOption("fade-out");
            alert(
                  "A reworking of Shakespeare's Sonnet 18 with the Fade-out Erasure Style. Click the document to write your own version of the poem!"
                );
            break;
    
        case "order":
            changeErasureOption("invisible");
            changeSelectionOption("word");
            alert("Executive Order 9066 authorized internment camps for Japansese-Americans during WWII. This example uses the editor's erasure technique to examine the language used in this historical text. Click the document to reveal the words that were erased.");
        break
    }    
    
}


export const internetPoet = () => {
    alert(
      "Write some heartfelt verse. Use lower case, Times New Roman. Upload an image using the background picture tool. Post on Instagram.\nThe poem was generated by a computer!"
    );
    const canvas = document.getElementById("targetText");
    window.clearText("targetText");
    canvas.style.width = "500px";
    canvas.style.height = "500px";
    canvas.style.backgroundColor = "white";
    canvas.style.whiteSpace = "pre-wrap";
    canvas.style.fontSize = "14px";
    window.generateText(
        "don’t mistake \nsalt for sugar \nit never really left the hands \nof those who broke you \nthe thing \nworth holding onto \nwould not come for you \nyour sweetness belongs \nonly to yourself \n"
    );
    canvas.style.backgroundImage = "url('/../images/cake.jpg')"
    canvas.style.fontFamily = "Times";
    changeSelectionOption("word");


    // canvas.childNodes.forEach((child) => {
    //   child.addEventListener("click", function () {
    //     if (window.erasureSelection === "character") {
    //     //   this.classList.toggle(`${window.erasureOption}`);
    //     } else {
    //       getWord(this).forEach((letterElement) => {
    //         //   debugger
    //         // letterElement.classList.toggle(`${window.erasureOption}`);
    //         // debugger
    //       });
    //     }
    //   });
    // });
};