// export const sonnet = () => {
//     const original = document.getElementById("targetText");
//     const sonnet = document.getElementById("sonnet");
//     const clone = sonnet.cloneNode(true)
//     original.replaceWith(clone)
//     document.getElementById("sonnet").id = "targetText"
//     alert("A reworking of Shakespeare's Sonnet 18 with the Fade-out Erasure Style.");



// }
export const demo = (name) => {
    const original = document.getElementById("targetText");
    const sonnet = document.getElementById(name);
    const clone = sonnet.cloneNode(true)
    original.replaceWith(clone)
    document.getElementById(name).id = "targetText"
    document.getElementById("targetText").childNodes.forEach( (child) => {
            child.addEventListener("click", function () {
              if (window.erasureSelection === "character") {
                this.classList.toggle(`${window.erasureOption}`);
              } else {
                getWord(this).forEach((letterElement) => {
                  letterElement.classList.toggle(`${window.erasureOption}`);
                });
              }
            });
    })

    switch (name) {
        case "sonnet":
            changeErasureOption("fade-out");
            alert(
                  "A reworking of Shakespeare's Sonnet 18 with the Fade-out Erasure Style."
                );
            break;
    
        case "order":
            changeErasureOption("invisible");
            changeSelectionOption("word");
            alert("Erasure Poem of Executive Order 9066 which authorized internment camps for Japansese-Americans during WWII");
        break
    }    
    
}


export const internetPoet = () => {
    alert("Poem text was generated by a AI!");
    const canvas = document.getElementById("targetText");
    window.clearText("targetText");
    canvas.style.width = "500px";
    canvas.style.height = "500px";
    canvas.style.backgroundColor = "white";
    canvas.style.whiteSpace = "pre-wrap";
    canvas.style.fontSize = "14px";
    window.generateText(
        "don’t mistake \nsalt for sugar \nit never really left the hands \nof those who broke you \nthe thing \nworth holding onto \nwould not come for you \nyour sweetness belongs \nonly to yourself \n"
    );
    canvas.style.backgroundImage = "url('../images/cake.jpg')"
    canvas.style.fontFamily = "Times";
    changeSelectionOption("word");


    // canvas.childNodes.forEach((child) => {
    //   child.addEventListener("click", function () {
    //     if (window.erasureSelection === "character") {
    //     //   this.classList.toggle(`${window.erasureOption}`);
    //     } else {
    //       getWord(this).forEach((letterElement) => {
    //         //   debugger
    //         // letterElement.classList.toggle(`${window.erasureOption}`);
    //         // debugger
    //       });
    //     }
    //   });
    // });
};